#
# POD
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: andrenho/coffee-io-k8s-backend:$VERSION
          ports:
            - containerPort: 8888
          resources:
            limits:
              memory: "32Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: LoadBalancer
  loadBalancerIP: $IP
